travis:
  secure:
    BINSTAR_TOKEN: A3RhzMza2l9gkwiIv3HDEV/WIJOqIm/hSJVatnLhy85drpvJ5ZBzQlCCBH8sMGWBkQLEJLfgJ9wBdPB/ghiGq40X8ZPtRXYXS5yQb6u06m6MG9T/hV9sup1/EfTMdlcniLZJIjbQ29Xq5O5gikelAyacLH+UOusgdz6rE16WDzmTSuJUCocWyUIejSY3XIZwOopo7rsvRRrPNhE+S4T7/vn3ZLOMtuSa0uBKlhWm9Q+S1bT6+cHsQJ82WtRceudb0Fw6qNauSyIjd2mOnhbRtJaOEUPuQVqMexpL31E4vNL2X7dFY81vSOfLPxr1emFldML+0zBeAZONtQJ2gKN0jrCkYqe6298JTc+xbG98ROR4irvbC0jCM1AA9mnKbnounf6v1HSSkXLtynaBUMhpvQ+PwebMpDF/OX6TdIGhe9FWnvcbsCCVaDPD0rvyDCM6XJFI+kExgyPB58oZsdOGtPuGNYb21wOtRInbGKN/Qkb/WoOP0E3QpxvT0/t71BNjJK5BFBLtr25p6JlGbnMf50IKHhREA78GrXUDX419UffRY7e0REFbKQFizgrEdHxXOSBOCHmiGnZO06V94bdqKDy3YRhC3b0a/8s8dou1xOzzLd1ET7EyRL0yvT+EB7rjbp8XLCrFhzLzMUj47DT0GTfWpxhpAlCTOJhJ3YcJ7WQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
